dataset:
  output_folder: data/raw/iris.csv
  train_data_folder: data/processed/train_data.csv
  train_labels_folder: data/processed/train_labels.csv
  test_data_folder: data/processed/test_data.csv
  test_labels_folder: data/processed/test_labels.csv
model:
  params:
    _target_: sklearn.neighbors.KNeighborsClassifier
    n_neighbors: 5
    algorithm: auto
    leaf_size: 30
    p: 2
  output_path: models/knn.pkl
evaluate:
  metrics: data/processed/metrics.json